import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Link from "next/link";
import { IoMdArrowBack } from "react-icons/io";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-auto max-w-sm bg-white">
      <div className="h-16 w-full bg-white flex items-center justify-start px-4 gap-4 shadow-md">
        <Link className="flex items-center" href="/">
          <IoMdArrowBack fontSize={24} />
        </Link>

        <p className="text-lg font-bold text-primary">Notification</p>
      </div>
      {children}
    </div>
  );
}
